repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.4
    hooks:
      - id: clang-format
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        types_or: ['c++', 'cuda']
        args: ['-p=build']
      - id: cppcheck
        args: ['--project=build/compile_commands.json', '--suppress=*:build/*']
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint

ci:
  skip:
    - clang-tidy
    - cppcheck
    - cmake-lint
