repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0
    hooks:
      - id: clang-format
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cppcheck
        args:
          - '--project=build/compile_commands.json'
          - '--suppress=*:build/*'
          - '--suppress=unusedFunction:*/*'
          - '--suppress=unreadVariable:tests/*'
          - '--suppress=missingIncludeSystem'
          - '--suppress=unmatchedSuppression'
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint

ci:
  skip:
    - cppcheck
    - cmake-lint
