name: recruit
channels:
  - conda-forge
dependencies:
  - compilers
  - python
  - cppcheck
  - clang-tools
  - cudatoolkit-dev
  - pre-commit
  - yamllint
  # Documentation
  - doxygen
  # Install Python dependencies only available on PyPI
  - pip
  - pip:
      - clang-format
      - cmakelang
      - flawfinder
