name: CI on DAS-5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  contents: read

jobs:
  ci-over-vpn:
    # Run if it is not a pull request
    # Run if is is a pull request from this repo
    if: github.event.name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    env:
      # This is the folder where the files will be copied and the CI will be run.
      folder-name: ci4gpu-${{ github.run_id }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Open VPN
        run: sudo apt-get install openvpn

      - name: Connect VPN
        id: connect_vpn
        timeout-minutes: 1
        run: |
          echo "${{ secrets.OVPN_FILE }}" | base64 -d > ./cert.ovpn
          sudo openvpn --config ./cert.ovpn --daemon
          until ip -f inet addr show tun0; do sleep 5; ip a; done

      - name: Copy files over ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: .
          target: ${{ env.folder-name }}
          overwrite: true

      - name: Run the CI script over ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.folder-name }}
            sh .github/ci-on-das.sh
            cat ci4gpu.log >> ../ci4gpu.log
            cd ..
            rm -rf ${{ env.folder-name }}
          script_stop: true # Stop after first failure

      - name: kill vpn
        if: always()
        run: sudo killall openvpn
