name: pre-commit

on:
  push:
  workflow_dispatch:

jobs:
  linting:
    name: run
    runs-on: ubuntu-latest
    steps:

      - name: Show git version
        shell: bash
        run: |
          which git
          git --version

      - name: Check out a copy of the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show some relevant env vars
        shell: bash
        run: |
          echo "GITHUB_BASE_REF = $GITHUB_BASE_REF"
          echo "GITHUB_HEAD_REF = $GITHUB_HEAD_REF"
          echo "GITHUB_REF_NAME = $GITHUB_REF_NAME"

      - name: Set the target and source refs if the trigger was a pull request
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          echo "precommit_from_ref=$GITHUB_BASE_REF" >> $GITHUB_ENV
          echo "precommit_to_ref=$GITHUB_HEAD_REF" >> $GITHUB_ENV

      - name: Set the target and source refs if the trigger was not a pull request
        if: ${{ github.event_name != 'pull_request' }}
        shell: bash
        run: |
          echo "precommit_from_ref=main" >> $GITHUB_ENV
          echo "precommit_to_ref=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Avoid problems with missing refs later
        shell: bash
        run: |
          git checkout ${{ env.precommit_from_ref }}
          git checkout ${{ env.precommit_to_ref }}

      - name: Install pre-commit
        shell: bash
        run: |
          sudo apt install python3 python3-pip
          python3 -m pip install pre-commit
          pre-commit install

      - name: Install dependencies and generate compilation database
        shell: bash
        run: |
          sudo apt install clang-tidy cppcheck nvidia-cuda-toolkit clang
          cmake -DCMAKE_CXX_COMPILER=clang++ -S . -B build

      - name: Run pre-commit on all files changed in this branch using project standard configuration
        shell: bash
        run: |
          git diff --name-only ${{ env.precommit_from_ref }}...${{ env.precommit_to_ref }}
          pre-commit run --from-ref ${{ env.precommit_from_ref }} --to-ref ${{ env.precommit_to_ref }}
